### PR TITLE
FEATURE Updated README.md file

### PR DESCRIPTION
**Pull request by Akshay-Rajeev-Nambiar**
updated read.md

### CODE REVIEW

**Comment by Akshay-krishna-R** [comment]
please delete line 2

**Review by ajeeshakshay — APPROVED** [review]
good to go

**Comment by Akshay-Rajeev-Nambiar** [comment]
Resolved issues with line 2

**Review by ajeeshakshay — CHANGES_REQUESTED** [review]
endha bro modayaaano?

**Review by ajeeshakshay — APPROVED** [review]

**Review by Akshay-krishna-R — APPROVED** [review]

**Pull request merged**
